# Config file for https://travis-ci.org/
#
# Based on https://github.com/wp-cli/sample-plugin/blob/master/.travis.yml
#   and https://github.com/ankurk91/codeception-travis-ci-example/blob/master/.travis.yml
#
# Validate this file here - http://lint.travis-ci.org/

sudo: false
language: php

dist: trusty
os:
  - linux

services:
  - mysql

addons:
  apt:
    packages:
      - google-chrome-stable

git:
  depth: 1

matrix:
  fast_finish: true
  include:
    - php: '7.1'
      env: WP_VERSION=latest
    - php: '7.1'
      env: WP_VERSION=4.8
    - php: '5.6'
      env: WP_VERSION=latest
    - php: '5.6'
      env: WP_VERSION=4.8
    - php: '5.4'
      env: WP_VERSION=latest
    - php: '5.4'
      env: WP_VERSION=4.8

before_install: phpenv config-rm xdebug.ini

install:
  - composer install --no-dev --prefer-dist --no-interaction

before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start

  - echo "Download selenium-server-standalone jar file"
  - wget -c -nc --retry-connrefused --tries=0 https://goo.gl/s4o9Vx -O selenium-server-standalone.jar

  - echo "Download chrome driver and unzip it"
  - wget -c -nc --retry-connrefused --tries=0 http://chromedriver.storage.googleapis.com/2.31/chromedriver_linux64.zip
  - unzip -o -q chromedriver_linux64.zip

  - echo "Run selenium server - background process"
  - nohup bash -c "java -Dwebdriver.chrome.driver=/full/path/to/chromedriver -jar selenium-server-standalone.jar &" && sleep 1; test -f nohup.out && cat nohup.out
  - ls -al

  - echo "Run php in-built server - background process"
  - nohup bash -c "php -S localhost:8000 2>&1 &" && sleep 1; test -f nohup.out && cat nohup.out

  - export PATH="$HOME/.composer/vendor/bin:$PATH"

script:
  - composer test

branches:
  only: test-ci

cache:
  directories:
    - vendor
    - $HOME/.composer/cache

notifications:
  slack:
    secure: Is16b7yl3I1k0Yul3xaBtCPhUoM7V9qOefNFN8RF8k7aDVsG4/nRaaOglgcW1GA4/AyfXK1DmiV/qFd5hQuSmyeujMeMnnNhD+8xoSy25LpkoC0WJ+16JzeH3DesSHCY5g2ujBBmdaisuAhg5T3uVkRaoAiXhcjLjIAJRFdMFy+pcwj2EhCKisShEsrymh5wsCbHsdm9ewzZUoa9Un9z1s5PgPlkwoWblD+NccE9hsLCUIj5szVealxg5yLFtEnAeCX9k1v0tWPfZpHZajr2tXN0FeBx/gsxFGC3Krx5dS9vI+ydPUJnEZgJwMGrCaNryLdhz8E4K4hv+878Xc5FgLl2kMaKQcmFFXcVCY7Ljuw2vVw68YOvickheQjKcuFUoqPjby9g3Q0rtW/lseev9A+u44my2o78af357cGolPHqCtrWgZwcsJDPUL00JfNkeikcn30jRAK4KUwFRdB3eDyZYhEajhALQK+Nn4Iw3mMJPSh6AMmg+vAQZWxw7E5hESfP4RUTzOlejHSMRoTQjwI9gNsxD5SGkjOfdhV0L3TasqpmRP1HmLxVXiXMB24eQ5nuxe++K7F18EYFkCK9eyI57EEbQe1VdjuoPQG6l+Btebff9EXhnMA8k/iQ6UCS8BfeK1d3oZjzo2O1J5AYvSw7LQPYJKI+Cfd9cGz+NG8=
