sudo: true

language: php

php:
    - "5.6"

env:
    - WP_VERSION=4.7 WP_MULTISITE=0 #Current stable release

matrix:
  include:
    - env: WP_VERSION=4.7 PHP_VERSION=7.1
    - env: WP_VERSION=4.7 PHP_VERSION=7.0
    - env: WP_VERSION=4.7 PHP_VERSION=5.6
    - env: WP_VERSION=4.7 PHP_VERSION=5.5
    - env: WP_VERSION=4.7 PHP_VERSION=5.4
    - env: WP_VERSION=4.7 PHP_VERSION=5.3
    - env: WP_VERSION=4.6 PHP_VERSION=5.6
    - env: WP_VERSION=4.5 PHP_VERSION=5.6
    - env: WP_VERSION=4.4 PHP_VERSION=5.6
    - env: WP_VERSION=4.3 PHP_VERSION=5.6
    - env: WP_VERSION=4.2 PHP_VERSION=5.6
    - env: WP_VERSION=4.1 PHP_VERSION=5.6
    - env: WP_VERSION=4.0 PHP_VERSION=5.6

before_script:
    - docker pull ostraining/phpfarm-wordpress-tests:4.7
    - docker pull ostraining/phpfarm-wordpress-tests:4.6
    - docker pull ostraining/phpfarm-wordpress-tests:4.5
    - docker pull ostraining/phpfarm-wordpress-tests:4.4
    - docker pull ostraining/phpfarm-wordpress-tests:4.3
    - docker pull ostraining/phpfarm-wordpress-tests:4.2
    - docker pull ostraining/phpfarm-wordpress-tests:4.1
    - docker pull ostraining/phpfarm-wordpress-tests:4.0
    - docker pull mysql:5.6

script: docker-compose up --abort-on-container-exit
