version: '2'

services:
    db:
        image: mysql:5.6
        restart: always
        environment:
             MYSQL_ROOT_PASSWORD: wordpress
             MYSQL_DATABASE: wordpress
             MYSQL_USER: wordpress
             MYSQL_PASSWORD: wordpress

    wp:
        image: ostraining/phpfarm-wordpress-tests:${WP_VERSION}
        ports:
            - 8053:8053
            - 8054:8054
            - 8055:8055
            - 8056:8056
            - 8070:8070
            - 8071:8071
        volumes:
            - .:/plugin
            - ./src:/var/www/src/wp-content/plugins/publishpress
        environment:
            PHP_VERSION: ${PHP_VERSION}
            WP_VERSION: ${WP_VERSION}
            DB_NAME: wordpress
            DB_USER: wordpress
            DB_PASSWORD: wordpress
        links:
            - db
        command: sh tests.sh
